// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEOZ4rBqoKqJDjoYycza2fpML6gIdUEf4',
    appId: '1:832433207149:web:2aea4e6bfcc664d8e0cc64',
    messagingSenderId: '832433207149',
    projectId: 'realstate-4564d',
    authDomain: 'realstate-4564d.firebaseapp.com',
    storageBucket: 'realstate-4564d.firebasestorage.app',
    measurementId: 'G-SFX5H50KQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMELCDISDehQ9KVP6RVekwwRHqTrJGZQ',
    appId: '1:832433207149:android:087f6b21a2d54df0e0cc64',
    messagingSenderId: '832433207149',
    projectId: 'realstate-4564d',
    storageBucket: 'realstate-4564d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIh3JCgzjlDYH8wa18N3E-py5dwfUH8SY',
    appId: '1:832433207149:ios:31e928de20b02a79e0cc64',
    messagingSenderId: '832433207149',
    projectId: 'realstate-4564d',
    storageBucket: 'realstate-4564d.firebasestorage.app',
    iosBundleId: 'com.example.real',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIh3JCgzjlDYH8wa18N3E-py5dwfUH8SY',
    appId: '1:832433207149:ios:31e928de20b02a79e0cc64',
    messagingSenderId: '832433207149',
    projectId: 'realstate-4564d',
    storageBucket: 'realstate-4564d.firebasestorage.app',
    iosBundleId: 'com.example.real',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEOZ4rBqoKqJDjoYycza2fpML6gIdUEf4',
    appId: '1:832433207149:web:c1f4e02885274063e0cc64',
    messagingSenderId: '832433207149',
    projectId: 'realstate-4564d',
    authDomain: 'realstate-4564d.firebaseapp.com',
    storageBucket: 'realstate-4564d.firebasestorage.app',
    measurementId: 'G-NSSZWDB6GL',
  );
}
